package client.services

/**
  * Created by shubham.k on 11-05-2016.
  */
object SessionItemName {
  val CONNECTION_LIST = "CONNECTION_LIST"
  val CURRENT_MESSAGE_LABEL_SEARCH = "CURRENT_MESSAGE_LABEL_SEARCH"
  val PREVIOUS_MESSAGE_LABEL_SEARCH = "PREVIOUS_MESSAGE_LABEL_SEARCH"
  val MESSAGE_SEARCH_CLICK = "MESSAGE_SEARCH_CLICK"
}
